### ISSUE TITLE
Peer to peer code review week4

### ISSUE THREAD

**Issue by aradradev** [olanikegloria/mobile-first#10]
**Agreed feddback**
     - 👍 Good job by adding the animation in the popUp window
     - You did an amazing job. Nice design 👍 and animation for the website 💯
     -You did an excellent job! The code is clean and the UI looks fantastic.👍 🔥
**Changes**
     - Kindly remove unused comments in your project since they can make your codebase look unclear. We can see you took so much effort into this project." 😁
     -  The code is clean and the UI looks fantastic.👍 🔥
     - check your code in the html file line 443

**Comment by HtetWaiYan7191** [comment]
You did an amazing job. Nice design 👍  and animation for the website 💯 . Kindly remove unused comments in your project since they can make your codebase look unclear. We can see you took so much effort into this project." 😁

**Comment by mutonic** [comment]
You did an excellent job! The code is clean and the UI looks fantastic.👍 🔥
